- name: add vhost dir
  file:
    path: /var/www/{{item}}/public_html
    owner: root
    group: root
    state: directory

- name: define dir with rights
  file:
    path: /var/www
    mode: 0755
    state: directory

- name: create home page
  template:
    src: index.html
    dest: /var/www/{{item}}/public_html/index.html

- name: create virtual host file
  template:
    src: vhost.conf
    dest: /etc/apache2/sites-available/{{ item }}.conf

- name: a2ensite {{ item }}
  command: a2ensite {{ item }}
  args:
    creates: /etc/apache2/sites-enabled/{{ item }}.conf
  notify:
    - restart apache2